t=int(input())
for _ in range(t):
    n,m=map(int,input().split())
    a=list(map(int,input().split()))
    b=list(map(int,input().split()))
    a.sort()
    b.sort(reverse=True)
    sb=sorted(b)
    c=sum((i+j)%m for i,j in zip(a,b))
    cb=sum((i+j)%m for i,j in zip(a,sb))
    print(min(c,cb))    